### PR TITLE
TravisCI reborn

### PR DESCRIPTION
**Pull request by szepeviktor**
Very much improved in every sense.

From https://github.com/szepeviktor/debian-server-tools/blob/master/.travis.yml

---
This change is [Reviewable](https://reviewable.io/reviews/voku/stringy/33)

### CODE REVIEW

**Comment by szepeviktor** [comment]
@voku Please ask for free open-source credits from TravisCI.
TravisCI is great! ☺️ 

See it in action: https://travis-ci.com/github/szepeviktor/Stringy/builds/219987421
(my TravisCI account has a **lot** of free credits)

**Comment by szepeviktor** [comment]
Big FAILURE 💥 TravisCI has all 3 extensions compiled in.
See `php -n -m` output: https://travis-ci.com/github/szepeviktor/Stringy/jobs/490710311#L226-L285

# 😢

**Comment by szepeviktor** [comment]
Success 🍏 
https://travis-ci.com/github/szepeviktor/Stringy/builds/219990510

> 1) StringyTest::testItCanUseNewEncoding
> UTF8::encode() without mbstring cannot handle "ASCII" encoding

Only 1 test fails.
Please help me.

**Comment by voku** [comment]
TravisCI isn't working for me, because of the limits they provided. I try to port my repos to GitHub Actions step-by-step. :-/

**Comment by szepeviktor** [comment]
All right. You have to know I'm a Travis fan. They give you open-source hours for free.

**Pull request closed without merging**
